# Generated by Django 4.2.3 on 2024-07-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_comment_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bidEnd',
            field=models.BooleanField(default=False),
        ),
    ]
