# Generated by Django 4.2.3 on 2024-07-02 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_item_bidend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='bidEnd',
            new_name='endBid',
        ),
    ]
