# Generated by Django 4.2.3 on 2024-07-04 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_bidend_item_endbid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
